version: "3.9"

services:

  calisim:
    image: ghcr.io/plant-food-research-open/calisim:${CALISIM_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: date -u +'%Y-%m-%dT%H:%M:%SZ'
        CALISIM_VERSION: ${CALISIM_VERSION:-latest}
        CALISIM_EXTRAS: -E hydra -E torchx
      tags:
        - ghcr.io/plant-food-research-open/calisim:latest
    volumes:
      - ./examples/outdir:/workspace/examples/outdir
      - ./tests:/workspace/tests

  calisim_torch:
    image: ghcr.io/plant-food-research-open/calisim-torch:${CALISIM_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: date -u +'%Y-%m-%dT%H:%M:%SZ'
        CALISIM_VERSION: ${CALISIM_VERSION:-latest}
        CALISIM_EXTRAS: -E hydra -E torchx -E torch
      tags:
        - ghcr.io/plant-food-research-open/calisim-torch:latest
    volumes:
      - ./examples/outdir:/workspace/examples/outdir
      - ./tests:/workspace/tests
