name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get tags
      run: git fetch --tags origin

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
         poetry install --no-interaction --no-root

    - name: Generate documentation
      run: |
        source .venv/bin/activate

        OUT_DIR=html
        rm -rf $OUT_DIR
        cd docs
        sphinx-multiversion source build/html
        cp index.html build/${OUT_DIR}
        mv build/${OUT_DIR} ..

    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        clean: false
        branch: gh-pages
        folder: html
