name: Test

on:
  release:
    types:
      - published
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
         poetry install --no-interaction -E torch

    - name: Test code
      if: github.event_name == 'push'
      run: |
        export CICD_TESTING_ENV=true

        source .venv/bin/activate
        pytest -v -n 8 --ignore=tests/functional --cov=calisim \
        --cov-report json --md-report --md-report-flavor gfm \
        --md-report-output md_report.md

    - name: Test code
      if: github.event_name != 'push'
      run: |
        export CICD_TESTING_ENV=true

        source .venv/bin/activate
        pytest -v -n 8 --cov=calisim --torch --cov-report json --md-report \
        --md-report-flavor gfm --md-report-output md_report.md

    - name: Update Coverage Badge
      if: matrix.python-version == 3.10 && (github.event_name == 'release' || github.event_name == 'workflow_dispatch')
      uses: we-cli/coverage-badge-action@main

    - name: Output reports to the job summary
      shell: bash
      run: |
        if [ -f md_report.md ]; then
          echo "<details><summary>Test Report</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat md_report.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Render the report to the PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Test Report
        recreate: true
        path: md_report.md
